version: '3'
services:
  web:
    build: .
    depends_on:
      - "postgres"
    links:
      - "postgres:postgres"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

